spring.application.name=auth-service

spring.datasource.url=jdbc:postgresql://localhost:5433/axiom_auth?TimeZone=UTC
spring.datasource.username= ${DB_USER:axiom}
spring.datasource.password= ${DB_PASS:changeme_local_dev}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:/db/migration

spring.grpc.server.port=9090

spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.password=changeme_local_dev

axiom.jwt.secret="this-is-a-local-dev-only-secret-change-it-before-any-real-deploy-32bytes+"
axiom.jwt.access-token-ttl-minutes=15
axiom.jwt.refresh-token-ttl-days=30

axiom.otp.ttl-minutes=5
axiom.otp.length=6