spring.config.import=file:.env[.properties]

spring.application.name=subscription-service

spring.datasource.url=jdbc:postgresql://localhost:5433/axiom_subscription?TimeZone=UTC
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASS}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:/db/migration

spring.grpc.server.port=9091

spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.password=${REDIS_PASS}


spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS}

spring.kafka.properties.security.protocol=SASL_SSL
spring.kafka.properties.sasl.mechanism=PLAIN

spring.kafka.properties.sasl.jaas.config=${KAFKA_SASL_JAAS_CONFIG}

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer